config/routes.rb
Rails.application.routes.draw do
  match 'todos/index', :as => :index, :via => [:post,:get,:patch]
  match "todos/create" => "todos#create", :via => [:post,:patch]
  match 'todos/complete' => 'todos#complete', :via => :post
  match 'todos/edit' => 'todos#edit', :via => :post, :as => :edit
  match 'todos/delete' => 'todos#delete', :via => :delete, :as => :delete

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	/attr_accessible :todo_item, :completed/
	validates :todo_item, presence: true
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo_items=Todo.all
    if(params[:id])
      @new_todo = Todo.find(params[:id])
      @nombre = "Save"
      @type = "Modify"
    else
      @new_todo = Todo.new
      @nombre = "Create"
      @type = "Insert"
    end
  end

  def create 
    if params[:back]
      redirect_to index_path
    else
      if params[:todo][:id].to_i>0
        t = Todo.find(params[:todo][:id])
        t.update_attribute(:todo_item, params[:todo][:todo_item])
        t.update_attribute(:todo_date, params[:todo][:todo_date])
        flash[:success] = "Item saved"
        redirect_to index_path
      else
      	todo = Todo.create(:todo_item => params[:todo][:todo_item],:todo_date => params[:todo][:todo_date],:completed => false)
      	todo.save
      	if !todo.valid?
      		flash[:error] = todo.errors.full_messages.join("<br>").html_safe
      	else
      		flash[:success] = "Added to list"
    	  end
    	  redirect_to index_path
      end
    end
   end

   def complete
    if(params[:todos_checkbox])
      if params[:toggle]
        params[:todos_checkbox].each do |check|
          todo_id = check
          t = Todo.find_by_id(todo_id)
          if t.completed
            t.update_attribute(:completed, false)
          else
            t.update_attribute(:completed, true)
          end
        end
        flash[:success] = "Items toggled"
      else
        params[:todos_checkbox].each do |check|
          todo_id = check
          t = Todo.find_by_id(todo_id)
          t.destroy
        end
        flash[:success] = "Items deleted"
      end
    else
      if params[:toggle]
        flash[:warning] = "Must select one or more items to toggle"
      else
        flash[:warning] = "Must select one or more items to destroy"
      end
    end
    redirect_to :action => 'index'
   end

   def delete
      Todo.find(params[:id]).destroy
      redirect_to index_path
   end

   def edit
      redirect_to index_path(:id => params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav <nav class="navbar navbar-inverse">
  <ul class="nav navbar-nav">
  <li role="presentation" class="container">
    <a href="#" style="font-size:1.5em">
      <b>
      Main
    </b>
    </a>
    <ul role="menu">
    </ul>
  </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<title>Shared Todo App </title>
<div class="container">
  <div class="row">
    <div class="span4">
      <h1>Shared Todo App</h1>
      <hr>
      <div class="form-group">
			<%= form_for @new_todo, :url => { :action => "create" }  do |f|  %>
        <p><%= @type %> your item's name</p>
    		  <%= f.text_field  :todo_item, class: "form-control" %>
        <br>
        <p><%= @type %> your item's due date</p>
          <%= f.date_field  :todo_date, class: "form-control" %>
        <br>
        <% if  @nombre == "Save" %>
          <%= f.hidden_field :id , :value => @new_todo.id %>
          <%= f.submit "Back", class: "btn btn-primary", name: 'back' %>
        <% else %>
          <%= f.hidden_field :id , :value => -1 %>
        <% end %>
    		<%= f.submit @nombre, class: "btn btn-success", name: 'submit' %>
 			<%end%>
      </div>
      <br>
      	<% if flash[:error] != nil %>
    		<div class="alert alert-danger">
      		<button type="button" class="close" data-dismiss="alert">×</button>
      		<strong><%= flash[:error] %></strong>
    		</div>
    		<% end %>
    	<% if flash[:success] != nil %>
   			<div class="alert alert-success">
   			<button type="button" class="close" data-dismiss="alert">×</button>
      		<strong><%= flash[:success] %></strong>
   			</div>
      <% end %>
      <% if flash[:warning] != nil %>
        <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">×</button>
          <strong><%= flash[:warning] %></strong>
        </div>
			<% end %>
      <p>All your todos here</p>
      <div class="well">
        <%= form_tag("/todos/complete/", :method => "post") do %>
        <ul style="list-style-type:none;">
        <% @todo_items.each do |t| %> 
          <% if t.completed == true %>
            <li style="color:grey;"> <%= check_box_tag  "todos_checkbox[]",t.id %>  <strike><%= t.todo_item %></strike>
             &nbsp|&nbsp <%= link_to "Destroy", delete_path(:id => t.id),:method => :delete, data: {confirm: "¿Are you sure?"} %>
            </li>
          <% else %>
            <% if t.todo_date && Date.today>t.todo_date %>
              <li style="color:red"> <%= check_box_tag  "todos_checkbox[]",t.id %> <%= t.todo_item %> &nbsp|&nbsp <%= t.todo_date %>
                &nbsp|&nbsp <%= link_to "Edit", edit_path(:id => t.id),:method => :post %> 
              </li>
            <% else %>
              <li> <%= check_box_tag  "todos_checkbox[]",t.id %> <%= t.todo_item %> 
                <% if t.todo_date %>
                  &nbsp|&nbsp <%= t.todo_date %>
                <% end %>
                &nbsp|&nbsp <%= link_to "Edit", edit_path(:id => t.id),:method => :post %> 
              </li>
            <% end %>
          <% end %>
        <% end %>
        </ul>
        <% if @todo_items.count > 0 %>
          <%= submit_tag("Toggle", :class=>"btn btn-primary", :name => 'toggle') %>
          <%= submit_tag("Delete", :class=>"btn btn-danger", :name => 'delete', data: {confirm: "¿Are you sure?"}) %>
        <% end %>
      <%end %>
      </div> <!-- well -->
    </div> <!-- span4 -->
  </div> <!-- row -->
</div> <!-- container -->